app:
  isProduction: false # TODO: temp
  prefix: "/api"
  port: 3000
sms:
  expireTime: 120 # 2 minutes
redis:
  port: 6379
  host: "localhost"
  password: "super_secret"
mongodb:
  uri: "mongodb://localhost:27017"
  username: "deliService"
  password: "super_secret"
  db: "deli"
auth:
  tokenSecretKey: "super_secret" # TODO: change later
  registrationTokenKey: "super_secret"
